version: "3"
services:
  gappuserredis:
    image: redis
    networks:
      - gappnetwork

  gappusermysql:
    image: mysql:5.6.43
    command: --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: Xjentj53Ijr
      MYSQL_DATABASE: gappuser
    volumes:
      - /gapp/user/mysql:/var/lib/mysql
    networks:
      - gappnetwork

  gappuser:
    image: aloxc/gappuser
    networks:
      - gappnetwork
    depends_on:
      - gappusermysql
      - gappuserredis
    expose:
      - 13331
    environment:
      REDIS_HOST : gappuserredis:6379
      REDIS_MAXIDLE : 1
      REDIS_MAXACTIVE : 10
      SERVER_PORT : 13331
      USER_MYSQL_DATABASE_NAME : gappuser
      USER_MYSQL_HOST : gappusermysql:3306
      USER_MYSQL_USER : root
      USER_MYSQL_PASSWORD : Xjentj53Ijr
      WAIT_MYSQL_SETUP_SECOND: 20

  gappordermysql:
    image: mysql:5.6.43
    command: --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: Jjke34jcjexje*d
      MYSQL_DATABASE: gapporder
    volumes:
      - /gapp/order/mysql:/var/lib/mysql
    networks:
      - gappnetwork

  gapporder:
    image: aloxc/gapporder
    networks:
      - gappnetwork
    depends_on:
      - gappordermysql
    expose:
      - 13331
    environment:
      SERVER_PORT : 13331
      ORDER_MYSQL_DATABASE_NAME : gapporder
      ORDER_MYSQL_HOST : gappordermysql:3306
      ORDER_MYSQL_USER : root
      ORDER_MYSQL_PASSWORD : Jjke34jcjexje*d
      WAIT_MYSQL_SETUP_SECOND: 20

  gappweb:
    image: aloxc/gappweb
    networks:
      - gappnetwork
    depends_on:
      - gapporder
      - gappuser
    ports:
      - 80:80
    environment:
      ORDER_SERVER_HOST: gapporder:13331
      USER_SERVER_HOST: gappuser:13331
      WEB_SERVER_PORT: ":80"
      
      
networks:
  gappnetwork:
    driver: bridge